# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Bing Today Img

# on:
#   schedule:
#     - cron: '0 21 * * *'    # 国际时间 21 点，估计北京时间 5点

on:
    push:
        branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITEE_TOKEN: ${{ secrets.GITEE }}
          
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run
      run: |
        python bingTodayImg.py
        
    - name: commit
      run: | 
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add today.png tv.m3u tv.txt
        git commit -m "generated"
        git push

        git clone https://${ACCESS_TOKEN}@github.com/shubihu/shubihu.github.io.git repo
        cp today.png repo/

        git clone https://${GITEE_TOKEN}@gitee.com/yahaha3195/tv.git
        cp tv.m3u tv/
        cp tv.txt tv/

        git config --global user.email "jrwjb@sina.com"
        git config --global user.name "shubihu"        
        cd repo
        git add today.png
        git commit -m "Add today.png"
        git push

        cd ~  
        cd tv
        git add tv.m3u tv.txt
        git commit -m "update"
        git push https://oauth2:${GITEE_TOKEN}@gitee.com/yahaha3195/tv.git
