# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Bing Today Img

# on:
#   schedule:
#     - cron: '0 21 * * *'    # 国际时间 21 点，估计北京时间 5点

on:
    push:
        branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run
      run: |
        python bingTodayImg.py
        
    - name: commit
      run: | 
        echo ${ACCESS_TOKEN}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add today.png
        git commit -m "generated"
        git push
        git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/shubihu/shubihu.github.io.git repo
        cp today.png repo/img/
        cd repo
        git checkout main
        git add img/today.png
        git commit -m "Add today.png to img folder"
        git push origin main
